
<<<<<<< HEAD
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:42)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:252)
	at app_kvClient.KVClient.main(KVClient.java:265)
2022-01-26 23:02:44,723 INFO  [main] root: Connection established.
2022-01-26 23:04:32,787 WARN  [main] root: Not connected to any store.
2022-01-26 23:04:40,117 WARN  [main] root: Not connected to any store.
2022-01-26 23:04:43,856 WARN  [main] root: Nothing was connected.
2022-01-26 23:04:48,682 INFO  [main] root: Printed out help.
2022-01-26 23:04:56,701 INFO  [main] root: Log level changed to level DEBUG
2022-01-26 23:05:02,692 INFO  [main] root: Log level changed to level ALL
2022-01-26 23:05:03,652 INFO  [main] root: Application exit.
2022-01-26 23:06:17,373 INFO  [main] root: Application exit.
2022-01-26 23:06:59,228 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:06:59,230 INFO  [main] root: Connection established.
2022-01-26 23:09:15,978 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:09:15,979 INFO  [main] root: Connection established.
2022-01-26 23:12:01,159 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:12:01,160 INFO  [main] root: Connection established.
2022-01-26 23:12:05,891 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:17:56,001 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:17:56,002 INFO  [main] root: Application exit.
2022-01-26 23:18:10,413 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:18:10,414 INFO  [main] root: Connection established.
2022-01-26 23:18:20,490 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:23:24,240 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:23:24,240 INFO  [main] root: Application exit.
2022-01-26 23:23:35,938 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:23:35,939 INFO  [main] root: Connection established.
2022-01-26 23:23:39,006 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:25:10,248 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:25:10,248 INFO  [main] root: Application exit.
2022-01-26 23:25:21,153 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:25:21,154 INFO  [main] root: Connection established.
2022-01-26 23:25:25,450 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:32:11,718 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:32:11,720 INFO  [main] root: Application exit.
2022-01-26 23:32:25,623 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:32:25,624 INFO  [main] root: Connection established.
2022-01-26 23:32:29,891 ERROR [main] root: java.lang.NullPointerException
2022-01-26 23:37:51,983 INFO  [main] root: Tearing down the connection ...
2022-01-26 23:37:51,983 INFO  [main] root: Application exit.
<<<<<<< HEAD
2022-01-26 23:57:18,134 INFO  [main] root: Connected to localhost on port 8008
2022-01-26 23:57:18,135 INFO  [main] root: Connection established.
2022-01-26 23:57:27,283 ERROR [main] root: java.lang.NullPointerException
2022-01-27 00:05:38,037 ERROR [main] root: Unknown command.
2022-01-27 00:12:39,809 INFO  [main] root: Tearing down the connection ...
2022-01-27 00:12:39,810 INFO  [main] root: Application exit.
2022-01-27 00:13:08,152 INFO  [main] root: Connected to localhost on port 8008
2022-01-27 00:13:08,153 INFO  [main] root: Connection established.
2022-01-27 00:13:12,414 ERROR [main] root: java.lang.NullPointerException
2022-01-27 00:14:56,103 INFO  [main] root: Tearing down the connection ...
2022-01-27 00:14:56,103 INFO  [main] root: Application exit.
=======
>>>>>>> 611cf7e6a927926d2ef3533d3e788bbcfbac5bcb
>>>>>>> 3cbdffa0809a779e96dbee603662638d4d4a5f4d
2022-01-27 13:42:58,663 ERROR [main] root: Invalid number of parameters!
2022-01-27 13:43:03,613 ERROR [main] root: Unknown command.
2022-01-27 13:43:08,661 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 13:43:08,661 INFO  [main] root: Connection established.
2022-01-27 13:44:55,616 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:254)
	at app_kvClient.KVClient.main(KVClient.java:267)
2022-01-27 13:44:55,626 INFO  [main] root: Connection established.
2022-01-27 13:45:25,647 ERROR [main] root: Unknown command.
2022-01-27 13:45:36,404 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:46:02,854 ERROR [main] root: Unknown command.
2022-01-27 13:46:05,250 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:46:19,854 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:46:19,854 INFO  [main] root: Disconnected.
2022-01-27 13:46:22,272 ERROR [main] root: Unknown command.
2022-01-27 13:46:27,731 ERROR [main] root: Unknown command.
2022-01-27 13:47:41,607 ERROR [main] root: Unknown command.
2022-01-27 13:47:53,064 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:254)
	at app_kvClient.KVClient.main(KVClient.java:267)
2022-01-27 13:47:53,068 INFO  [main] root: Connection established.
2022-01-27 13:47:57,704 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:49:28,428 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:49:28,431 INFO  [main] root: Connection established.
2022-01-27 13:49:37,321 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:50:47,010 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:258)
	at app_kvClient.KVClient.main(KVClient.java:271)
2022-01-27 13:50:47,019 INFO  [main] root: Connection established.
2022-01-27 13:50:53,127 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:52:41,657 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:52:41,659 INFO  [main] root: Application exit.
2022-01-27 13:52:55,320 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:258)
	at app_kvClient.KVClient.main(KVClient.java:271)
2022-01-27 13:52:55,327 INFO  [main] root: Connection established.
2022-01-27 13:52:58,265 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:53:51,619 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:53:51,620 INFO  [main] root: Application exit.
2022-01-27 13:54:10,401 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:54:10,408 INFO  [main] root: Connection established.
2022-01-27 13:54:13,289 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:55:20,355 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:55:20,355 INFO  [main] root: Application exit.
2022-01-27 13:56:03,628 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:56:03,632 INFO  [main] root: Connection established.
2022-01-27 13:56:06,395 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:57:18,212 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:57:58,297 INFO  [main] root: Tearing down the connection ...
2022-01-27 13:57:58,298 INFO  [main] root: Application exit.
2022-01-27 13:58:33,763 ERROR [main] root: Invalid number of parameters!
2022-01-27 13:58:36,335 ERROR [main] root: Unknown command.
2022-01-27 13:58:42,175 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 13:58:42,183 INFO  [main] root: Connection established.
2022-01-27 13:58:45,018 ERROR [main] root: java.lang.NullPointerException
2022-01-27 13:58:48,805 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:08:16,430 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 14:08:16,442 INFO  [main] root: Connection established.
2022-01-27 14:08:32,442 ERROR [main] root: Unknown command.
2022-01-27 14:08:33,706 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:08:33,706 INFO  [main] root: Application exit.
2022-01-27 14:08:47,233 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:08:47,245 INFO  [main] root: Connection established.
2022-01-27 14:08:51,727 ERROR [main] root: java.io.IOException: Connection is already established
2022-01-27 14:08:56,207 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:09:03,884 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:09:58,157 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:09:58,158 INFO  [main] root: Application exit.
2022-01-27 14:10:40,536 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:10:40,673 INFO  [main] root: Connection established.
2022-01-27 14:10:46,441 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:10:50,476 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:12:58,764 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:12:58,764 INFO  [main] root: Application exit.
2022-01-27 14:13:46,782 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:13:46,816 INFO  [main] root: Connection established.
2022-01-27 14:13:54,941 ERROR [main] root: java.lang.NullPointerException
<<<<<<< HEAD
2022-01-27 14:21:15,053 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:21:15,056 INFO  [main] root: Connection established.
2022-01-27 14:21:55,478 ERROR [main] root: java.io.IOException: Connection is already established
2022-01-27 14:23:29,812 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:23:29,813 INFO  [main] root: Application exit.
=======
2022-01-27 14:25:31,614 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:25:31,615 INFO  [main] root: Connection established.
2022-01-27 14:25:35,997 ERROR [main] root: java.lang.NullPointerException
<<<<<<< HEAD
2022-01-27 14:30:18,791 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:30:18,793 INFO  [main] root: Connection established.
2022-01-27 14:30:21,944 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:31:17,399 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:31:17,405 INFO  [main] root: Connection established.
2022-01-27 14:31:21,051 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:32:05,559 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:32:05,560 INFO  [main] root: Disconnected.
2022-01-27 14:32:07,169 INFO  [main] root: Application exit.
2022-01-27 14:32:38,111 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:32:38,112 INFO  [main] root: Connection established.
2022-01-27 14:32:39,736 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:36:30,516 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:36:30,517 INFO  [main] root: Connection established.
2022-01-27 14:36:32,396 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:37:33,251 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:37:33,252 INFO  [main] root: Connection established.
2022-01-27 14:37:35,363 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:39:02,611 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:39:02,612 INFO  [main] root: Connection established.
2022-01-27 14:39:05,055 ERROR [main] root: java.lang.NullPointerException
=======
>>>>>>> 7bf807522ac88494cbd865158d722872c24db65b
>>>>>>> 9b9b766de0bfdd97d701353f76d6d241e541f662
<<<<<<< HEAD
2022-01-27 14:45:09,136 INFO  [main] root: Application exit.
2022-01-27 14:47:50,391 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:255)
	at app_kvClient.KVClient.main(KVClient.java:268)
2022-01-27 14:47:50,394 INFO  [main] root: Connection established.
2022-01-27 14:48:24,935 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:48:24,935 INFO  [main] root: Application exit.
2022-01-27 14:48:37,704 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:29)
	at app_kvClient.KVClient.handleCommand(KVClient.java:63)
	at app_kvClient.KVClient.run(KVClient.java:257)
	at app_kvClient.KVClient.main(KVClient.java:270)
2022-01-27 14:48:37,707 INFO  [main] root: Connection established.
2022-01-27 14:49:18,186 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:49:18,186 INFO  [main] root: Application exit.
2022-01-27 14:50:17,660 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 14:50:17,663 INFO  [main] root: Connection established.
2022-01-27 14:52:05,755 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:52:05,755 INFO  [main] root: Application exit.
2022-01-27 14:56:29,977 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 14:56:29,980 INFO  [main] root: Connection established.
2022-01-27 14:56:59,766 INFO  [main] root: Tearing down the connection ...
2022-01-27 14:56:59,766 INFO  [main] root: Application exit.
=======
2022-01-27 14:42:10,567 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:42:10,568 INFO  [main] root: Connection established.
2022-01-27 14:42:13,584 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:46:46,085 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:46:46,086 INFO  [main] root: Connection established.
2022-01-27 14:46:49,701 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:50:16,219 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:50:16,225 INFO  [main] root: Connection established.
2022-01-27 14:50:18,798 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:51:39,225 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:51:39,227 INFO  [main] root: Connection established.
2022-01-27 14:51:41,489 ERROR [main] root: java.lang.NullPointerException
2022-01-27 14:53:49,051 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 14:53:49,052 INFO  [main] root: Connection established.
2022-01-27 14:53:51,938 ERROR [main] root: java.lang.NullPointerException
<<<<<<< HEAD
>>>>>>> 211186be0f2dc3311440d8d23e4b5d80be1c0626
2022-01-27 15:00:53,045 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 15:00:53,048 INFO  [main] root: Connection established to 127.0.0.1:8008
2022-01-27 15:01:09,393 ERROR [main] root: java.io.IOException: Connection is already established
2022-01-27 15:08:10,548 INFO  [main] root: Tearing down the connection ...
2022-01-27 15:08:10,548 INFO  [main] root: Application exit.
2022-01-27 15:08:34,216 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:31)
	at app_kvClient.KVClient.handleCommand(KVClient.java:67)
	at app_kvClient.KVClient.run(KVClient.java:259)
	at app_kvClient.KVClient.main(KVClient.java:272)
2022-01-27 15:08:34,219 INFO  [main] root: Connection established to 127.0.0.1:8008
2022-01-27 15:09:09,256 INFO  [main] root: Tearing down the connection ...
2022-01-27 15:09:09,256 INFO  [main] root: Application exit.
2022-01-27 15:09:20,522 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:31)
	at app_kvClient.KVClient.handleCommand(KVClient.java:70)
	at app_kvClient.KVClient.run(KVClient.java:262)
	at app_kvClient.KVClient.main(KVClient.java:275)
2022-01-27 15:09:20,526 INFO  [main] root: Connection established to 127.0.0.1:8008
2022-01-27 15:09:43,893 INFO  [main] root: Tearing down the connection ...
2022-01-27 15:09:43,893 INFO  [main] root: Application exit.
2022-01-27 15:09:52,777 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:31)
	at app_kvClient.KVClient.handleCommand(KVClient.java:70)
	at app_kvClient.KVClient.run(KVClient.java:262)
	at app_kvClient.KVClient.main(KVClient.java:275)
2022-01-27 15:09:52,780 INFO  [main] root: Connection established to 127.0.0.1:8008
2022-01-27 15:10:32,464 INFO  [main] root: Tearing down the connection ...
2022-01-27 15:10:32,464 INFO  [main] root: Application exit.
2022-01-27 15:10:42,333 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:69)
	at app_kvClient.KVClient.run(KVClient.java:261)
	at app_kvClient.KVClient.main(KVClient.java:274)
2022-01-27 15:10:42,337 ERROR [main] root: java.net.ConnectException: Connection refused (Connection refused)
2022-01-27 15:11:12,179 INFO  [main] root: Application exit.
2022-01-27 15:11:22,944 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 15:11:22,947 ERROR [main] root: java.net.ConnectException: Connection refused (Connection refused)
2022-01-27 15:11:55,579 INFO  [main] root: Application exit.
2022-01-27 15:12:05,162 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 15:12:05,164 ERROR [main] root: Something went wrong! 
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at java.base/java.net.Socket.connect(Socket.java:557)
	at java.base/java.net.Socket.<init>(Socket.java:453)
	at java.base/java.net.Socket.<init>(Socket.java:230)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 15:12:43,265 INFO  [main] root: Connected to localhost on port 8008
2022-01-27 15:12:43,265 INFO  [main] root: Connection established to 127.0.0.1:8008
2022-01-27 15:13:03,912 ERROR [main] root: java.lang.NullPointerException
2022-01-27 15:14:21,475 ERROR [main] root: java.lang.NullPointerException
2022-01-27 15:14:30,008 ERROR [main] root: java.lang.NullPointerException
2022-01-27 15:14:34,565 INFO  [main] root: Printed out help.
2022-01-27 15:25:02,616 INFO  [main] root: Tearing down the connection ...
2022-01-27 15:25:02,617 INFO  [main] root: Application exit.
=======
2022-01-27 15:03:00,510 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 15:03:00,511 INFO  [main] root: Connection established.
2022-01-27 15:03:02,890 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","sandra":"hi",}'
2022-01-27 15:03:02,890 ERROR [main] root: java.lang.NullPointerException
2022-01-27 15:22:40,403 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 15:22:40,405 INFO  [main] root: Connection established.
2022-01-27 15:22:43,371 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","sandra":"hi",}'
2022-01-27 15:22:43,371 ERROR [main] root: java.lang.NullPointerException
=======
>>>>>>> 9c762937efafe34de4d0c409e757d1cbae217e23
<<<<<<< HEAD
2022-01-27 15:44:28,841 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 15:44:28,842 INFO  [main] root: Connection established.
2022-01-27 15:44:33,543 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 15:44:33,543 ERROR [main] root: java.lang.NullPointerException
=======
>>>>>>> ce7ad189f2e45a5136302ce5d90bcc1c7027ab35
>>>>>>> 7036b79510230a26805a88e742e65d321f5879bf
2022-01-27 15:53:35,011 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 15:53:35,012 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 15:53:37,507 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 15:53:37,507 ERROR [main] root: java.lang.NullPointerException
2022-01-27 15:54:26,519 ERROR [main] root: Invalid number of parameters!
2022-01-27 15:54:28,608 ERROR [main] root: Unknown command.
2022-01-27 15:54:32,919 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 15:54:32,919 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 15:54:35,032 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 15:54:35,032 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:12:26,945 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:12:26,946 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:12:45,094 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:12:45,095 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:13:29,262 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:13:29,263 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:13:32,830 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:13:32,830 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:14:17,546 ERROR [main] root: Error! Unable to establish connection. 

java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 16:14:17,551 ERROR [main] root: Something went wrong! 
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at client.KVStore.connect(KVStore.java:45)
	at app_kvClient.KVClient.newConnection(KVClient.java:30)
	at app_kvClient.KVClient.handleCommand(KVClient.java:64)
	at app_kvClient.KVClient.run(KVClient.java:256)
	at app_kvClient.KVClient.main(KVClient.java:269)
2022-01-27 16:14:23,692 ERROR [main] root: Unknown command.
2022-01-27 16:14:32,107 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:14:32,107 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:14:34,644 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:14:34,644 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:16:02,532 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:16:02,533 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:16:05,045 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:16:05,045 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:17:03,112 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:17:03,113 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:17:18,677 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:17:18,677 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:18:48,227 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:18:48,228 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:18:50,263 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:18:50,263 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:25:56,347 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:25:56,348 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:25:58,085 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:25:58,086 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:27:25,437 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:27:25,439 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:27:27,791 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:27:27,791 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:31:20,657 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:31:20,658 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:31:23,538 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:31:23,539 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:32:39,677 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:32:39,678 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:32:42,157 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:32:42,157 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:33:11,057 ERROR [main] root: Unknown command.
2022-01-27 16:33:19,190 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:33:19,191 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:33:21,422 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:33:21,423 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:34:37,856 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:34:37,858 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:34:40,315 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:34:40,315 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:35:38,671 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:35:38,672 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:35:41,069 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:35:41,070 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:36:48,062 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:36:48,063 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:36:53,183 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 16:36:53,183 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:43:35,075 ERROR [main] root: Invalid number of parameters!
2022-01-27 16:43:40,105 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:43:40,105 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:43:44,100 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 16:43:44,101 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:44:41,749 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:44:41,750 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:44:44,658 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 16:44:44,658 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:51:48,151 ERROR [main] root: Unknown command.
2022-01-27 16:51:56,559 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:51:56,561 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:51:59,604 ERROR [main] root: Unknown command.
2022-01-27 16:52:07,997 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 16:52:07,997 ERROR [main] root: java.lang.NullPointerException
2022-01-27 16:56:13,780 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 16:56:13,782 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 16:56:16,566 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 16:56:16,566 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:01:04,495 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:01:04,496 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:01:07,137 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:01:07,137 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:03:27,731 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:03:27,732 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:03:32,429 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:03:32,429 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:10:55,323 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:10:55,323 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:10:57,697 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:10:57,698 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:13:31,899 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:13:31,900 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:13:36,107 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:13:36,107 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:15:26,611 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:15:26,611 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:15:30,577 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:15:30,578 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:16:46,851 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:16:46,851 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:16:49,507 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:16:49,507 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:18:24,498 ERROR [main] root: Unknown command.
2022-01-27 17:18:32,080 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:18:32,080 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:18:35,192 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:18:35,192 ERROR [main] root: java.lang.NullPointerException
2022-01-27 17:26:35,084 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 17:26:35,085 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 17:26:38,820 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 17:26:38,820 ERROR [main] root: java.lang.NullPointerException
2022-01-27 20:02:22,142 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:02:22,143 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:02:27,157 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra love",}'
2022-01-27 20:02:27,158 ERROR [main] root: java.lang.NullPointerException
2022-01-27 20:06:46,383 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:06:46,384 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:06:50,443 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 20:06:50,445 ERROR [main] root: java.lang.NullPointerException
2022-01-27 20:08:11,207 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:08:11,210 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:08:14,643 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","he":"saner",}'
2022-01-27 20:08:14,644 ERROR [main] root: java.lang.NullPointerException
2022-01-27 20:09:51,030 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:09:51,031 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:09:53,624 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hi":"sandra",}'
2022-01-27 20:09:53,625 ERROR [main] root: java.lang.NullPointerException
2022-01-27 20:10:55,521 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:10:55,522 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:10:59,553 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hey":"sandra",}'
2022-01-27 20:10:59,556 ERROR [main] root: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
2022-01-27 20:13:20,461 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","heu":"u",}'
2022-01-27 20:13:20,464 ERROR [main] root: java.lang.IllegalArgumentException: No enum constant shared.messages.KVMessage.StatusType.status
2022-01-27 20:18:19,805 ERROR [main] root: Unknown command.
2022-01-27 20:18:26,707 INFO  [main] root: Application exit.
2022-01-27 20:20:33,819 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:20:33,820 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:20:50,377 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hello":"sandra love",}'
2022-01-27 20:20:50,378 ERROR [main] root: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
2022-01-27 20:22:31,741 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:22:31,741 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:22:35,535 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hello":"sandra love",}'
2022-01-27 20:22:35,537 ERROR [main] root: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
2022-01-27 20:24:04,545 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:24:04,546 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:24:08,893 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hello":"sandra love",}'
2022-01-27 20:24:08,895 ERROR [main] root: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
2022-01-27 20:26:02,873 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:26:02,874 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:26:06,365 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","hello":"sandra love",}'
2022-01-27 20:26:06,377 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","hello":""}'
2022-01-27 20:26:06,377 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 20:30:59,009 ERROR [main] root: Unknown command.
2022-01-27 20:31:04,113 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:31:04,115 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:31:06,158 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:31:06,179 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 20:31:06,180 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 20:33:07,562 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:33:07,564 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:33:09,919 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:33:09,926 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 20:33:09,926 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 20:33:17,419 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:33:17,420 INFO  [main] root: 
2022-01-27 20:35:00,382 WARN  [main] root: Not connected to any store.
2022-01-27 20:35:02,973 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:35:02,973 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:35:10,595 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:35:10,609 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 20:35:10,609 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 20:35:25,847 ERROR [main] root: Unknown command.
2022-01-27 20:35:27,806 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:35:27,806 INFO  [main] root: 
2022-01-27 20:48:55,756 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:48:55,758 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:48:57,598 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:48:57,607 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 20:48:57,607 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 20:49:02,450 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:49:02,450 INFO  [main] root: 
2022-01-27 20:51:11,099 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:57:24,240 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 20:57:24,241 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 20:57:28,841 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:57:28,878 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 20:57:28,878 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 20:57:32,594 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 20:57:32,594 INFO  [main] root: 
2022-01-27 21:02:03,233 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:02:03,234 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:02:05,546 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:02:05,559 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:02:05,559 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:02:58,794 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:02:58,795 INFO  [main] root: 
2022-01-27 21:06:30,660 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:06:30,661 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:06:34,932 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:06:34,966 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:06:34,966 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:06:41,020 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:06:41,020 INFO  [main] root: 
2022-01-27 21:12:52,587 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:12:52,587 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:12:55,748 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:12:55,785 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:12:55,786 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:13:04,803 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:13:04,804 INFO  [main] root: 
2022-01-27 21:14:46,109 WARN  [main] root: Not connected to any store.
2022-01-27 21:14:49,083 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:14:49,084 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:14:51,724 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:14:51,772 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:14:51,772 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:14:58,791 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:14:58,792 INFO  [main] root: 
2022-01-27 21:17:10,175 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:17:10,175 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:17:13,108 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:17:13,124 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:17:13,125 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:17:18,005 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:17:18,006 INFO  [main] root: 
2022-01-27 21:18:59,049 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:18:59,050 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:19:03,894 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:19:03,931 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:19:03,932 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:19:07,628 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:19:07,629 INFO  [main] root: 
2022-01-27 21:20:15,993 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:20:15,996 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:20:17,997 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:20:18,007 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:20:18,007 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:20:19,395 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:20:19,395 INFO  [main] root: 
2022-01-27 21:22:03,672 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:22:03,673 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:22:05,145 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:22:05,155 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:22:05,156 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:22:06,871 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:22:06,871 INFO  [main] root: 
2022-01-27 21:23:18,717 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:23:18,742 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:23:20,490 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:23:20,515 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:23:20,516 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:23:22,593 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:23:22,594 INFO  [main] root: 
2022-01-27 21:24:44,604 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:24:44,605 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:24:47,705 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:24:47,732 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:24:47,732 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:24:57,297 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:24:57,298 INFO  [main] root: 
2022-01-27 21:26:01,143 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:26:01,144 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:26:03,476 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:26:03,507 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:26:03,507 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:26:06,286 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:26:06,287 INFO  [main] root: 
2022-01-27 21:27:01,748 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:27:01,750 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:27:03,659 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:27:03,669 ERROR [main] root: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
2022-01-27 21:27:05,732 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:27:05,732 INFO  [main] root: 
2022-01-27 21:28:50,084 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:28:50,132 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:28:51,637 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:28:51,661 ERROR [main] root: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
2022-01-27 21:32:38,210 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:32:38,212 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:32:50,228 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:32:50,247 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_UPDATE","a":"b",}'
2022-01-27 21:32:50,248 INFO  [main] root: shared.messages.JSONMessage@1d16f93d
2022-01-27 21:33:16,437 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"GET","a":""}'
2022-01-27 21:33:16,439 DEBUG [main] root: jsonStr is null :/
2022-01-27 21:33:16,439 INFO  [main] root: 
2022-01-27 21:33:36,737 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:33:36,747 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_SUCCESS","j":"k",}'
2022-01-27 21:33:36,747 INFO  [main] root: shared.messages.JSONMessage@67b92f0a
2022-01-27 21:33:45,728 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"GET","j":""}'
2022-01-27 21:33:45,728 DEBUG [main] root: jsonStr is null :/
2022-01-27 21:33:45,728 INFO  [main] root: 
2022-01-27 21:40:08,145 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:40:08,149 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:40:10,920 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","j":"k",}'
2022-01-27 21:40:10,939 DEBUG [main] root: No value given
2022-01-27 21:40:10,940 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","j":""}'
2022-01-27 21:40:10,945 INFO  [main] root: shared.messages.JSONMessage@2b9627bc
2022-01-27 21:40:17,618 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"GET","j":""}'
2022-01-27 21:40:17,618 DEBUG [main] root: jsonStr is null :/
2022-01-27 21:40:17,618 INFO  [main] root: 
2022-01-27 21:42:54,629 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:42:54,635 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:42:56,388 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:42:56,398 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:42:56,398 INFO  [main] root: shared.messages.JSONMessage@2b9627bc
2022-01-27 21:46:30,504 INFO  [main] root: Connected to localhost on port 8080
2022-01-27 21:46:30,504 INFO  [main] root: Connection established to 127.0.0.1:8080
2022-01-27 21:46:32,949 INFO  [main] root: SEND 	<127.0.0.1:8080>: '{"status":"PUT","a":"b",}'
2022-01-27 21:46:32,972 INFO  [main] root: RECEIVE 	<127.0.0.1:8080>: '{"status":"PUT_ERROR","a":""}'
2022-01-27 21:46:32,973 INFO  [main] root: shared.messages.JSONMessage@2b9627bc
